### ISSUE TITLE
AdWords integration does not support dynamic remarketing

### ISSUE THREAD

**Issue by LaurentVB** [segment-integrations/analytics.js-integration-adwords#2]
Hello,

Looking to replace our copy/pasta tracking code for adwords with one more segment integration, I want to emulate the dynamic remarketing parameters we already use.

Unfortunately, I see in https://github.com/segment-integrations/analytics.js-integration-adwords/blob/master/lib/index.js#L52-L61 that `google_custom_params` is always set to an empty hash called `props`.

Adwords remarketing documentation (https://developers.google.com/adwords-remarketing-tag/) uses (and even recommends) a global variable called `google_tag_params` so that's probably what most people are doing anyway. 
An easy fix to support dynamic remarketing could be:

``` Javascript
AdWords.prototype.page = function() {
  var remarketing = !!this.options.remarketing;
  var id = this.options.conversionId;
  var props = window.google_tag_params || {};
  window.google_trackConversion({
    google_conversion_id: id,
    google_custom_params: props,
    google_remarketing_only: remarketing
  });
};
```

BTW, kudos on making your integrations open source.

Regards, 

Laurent

**Comment by sperand-io** [comment]
@LaurentVB thanks for the flag and suggestion! Typically, we don't like to rely on anything on the window, but as that's the usual approach for adwords I don't see why we wouldn't do this to at least respect whatever people are populating that variable with for now. 

In the future we should facilitate some proper mapping :)

**Comment by sperand-io** [comment]
If you're interested in contributing, a PR may expedite this getting shipped and will definitely warrant a tshirt in the mail! :)

**Comment by LaurentVB** [comment]
The t-shirt made me do it #4

**Comment by hankim813** [comment]
Hey @LaurentVB Thanks for reporting this. We just shipped a fix for this with #10!

Will also close your PR #4 

As for your free t-shirt, if you send han@segment.com an email, I'll send you one!

**Comment by taensch** [comment]
Hi @hankim813! 
Thanks for implementing dynamic remarketing! 
We're trying to use it, however there is no documentation on that on Segment.  
We hardcoded the custom google_tag_params before the segment snippet. This does not work, parameters are not being passed.  
Is it than sending them in a track/page call upon every page load, and if yes, using any specific key? Asked Segment&Adwords support already, without success so far. 
You'd help us greatly!
Tanja from Jobable

**Comment by hankim813** [comment]
hey @taensch sorry about that -- we did have a section for it in the docs, but didn't make it clear. I've updated it now: https://segment.com/docs/integrations/adwords/#dynamic-remarketing-tags

let me know if you are still having issues!

**Comment by taensch** [comment]
Hi @hankim813! 
That's great news! Thank you very much. 
We'll try to implement!
