### ISSUE TITLE
google_trackConversion is not a function

### ISSUE THREAD

**Issue by ertrzyiks** [segment-integrations/analytics.js-integration-adwords#6]
I see following exception on production:

`TypeError: window.google_trackConversion is not a function`

I've made a little investigation and I'm wondering, could it be possible that there is something wrong with an initialization?

I see some other integration initialize itself checking `loaded` state:
- https://github.com/segment-integrations/analytics.js-integration-amplitude/blob/master/lib/index.js#L78
- https://github.com/segment-integrations/analytics.js-integration-qualaroo/blob/7baa8a10eceba4ce5530d8e89cedafe053c1eafb/lib/index.js#L33

**Comment by zowers** [comment]
we are also getting it

**Comment by cr0t** [comment]
Hey there.

These errors you may experience when you (or your site client) use privacy extensions like Disconnect for Chrome (https://chrome.google.com/webstore/detail/disconnect/jeoacafpbcihiomhlakheieifhpjdfeo?hl=en), or similar.

Maybe, you should add a check to your code to prevent issues like this.

**Comment by zowers** [comment]
@cr0t yes, thanks, we were able to reproduce it once (but once only)

**Comment by kellyrmilligan** [comment]
@cr0t what sort of check do you recommend?

**Comment by cr0t** [comment]
@kellyrmilligan if we talk about Segment integration JS code, then it might be useful to add something like `if (typeof window.google_trackConversion !== undefined) {}` check before the code wants to use it?

**Comment by kellyrmilligan** [comment]
We're just calling track like normal, and the integration seems to be calling it without checking if it's there. It's assuming I believe that you have it loaded already.

**Comment by kellyrmilligan** [comment]
Should I for my case not send it to tie integration?

**Comment by cr0t** [comment]
@kellyrmilligan I'm pretty sure that this should be done on the `segment-integration/analytics.js-integration-adwords` side.

More than that @ertrzyiks already mentioned this PR https://github.com/segment-integrations/analytics.js-integration-adwords/pull/7 here to resolve the issue.

The team of segment integration should pay more attention here (but I don't know how to call them here).

**Comment by markwpiper** [comment]
I tried contacting segment support about this. 

Here is the link so you can put a ticket in w/ them as well:
https://segment.com/help/contact
